name: Adds all issues to project board

on:
  issues:
    types:
      - opened
      - edited

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.5
        with:
          project-url: https://github.com/orgs/App-Ringer/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
